// <auto-generated />
using System;
using Aros.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Aros.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260902152448_RemoveJapaneseVocab")]
    partial class RemoveJapaneseVocab
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Aros.Api.Data.Entities.HomophoneGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Characters")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reading")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Characters")
                        .IsUnique();

                    b.ToTable("HomophoneGroups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Characters = "他她它",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Reading = "tā"
                        },
                        new
                        {
                            Id = 2,
                            Characters = "你妳",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Reading = "nǐ"
                        },
                        new
                        {
                            Id = 3,
                            Characters = "的得地",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Reading = "de"
                        },
                        new
                        {
                            Id = 4,
                            Characters = "在再",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Reading = "zài"
                        },
                        new
                        {
                            Id = 5,
                            Characters = "是事",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Reading = "shì"
                        },
                        new
                        {
                            Id = 6,
                            Characters = "做作",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Reading = "zuò"
                        });
                });

            modelBuilder.Entity("Aros.Api.Data.Entities.ListeningAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AnsweredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Correct")
                        .HasColumnType("boolean");

                    b.Property<int>("TtsClipId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AnsweredAt");

                    b.HasIndex("TtsClipId");

                    b.ToTable("ListeningAnswers");
                });

            modelBuilder.Entity("Aros.Api.Data.Entities.TtsClip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("DurationSeconds")
                        .HasColumnType("double precision");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Sentence")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Voice")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Sentence")
                        .IsUnique();

                    b.ToTable("TtsClips");
                });

            modelBuilder.Entity("Aros.Api.Data.Entities.TtsClipStat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ConsecutiveCorrect")
                        .HasColumnType("integer");

                    b.Property<int>("CorrectCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TtsClipId")
                        .HasColumnType("integer");

                    b.Property<int>("WrongCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TtsClipId")
                        .IsUnique();

                    b.ToTable("TtsClipStats");
                });

            modelBuilder.Entity("Aros.Api.Data.Entities.ListeningAnswer", b =>
                {
                    b.HasOne("Aros.Api.Data.Entities.TtsClip", "TtsClip")
                        .WithMany()
                        .HasForeignKey("TtsClipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TtsClip");
                });

            modelBuilder.Entity("Aros.Api.Data.Entities.TtsClipStat", b =>
                {
                    b.HasOne("Aros.Api.Data.Entities.TtsClip", "TtsClip")
                        .WithOne("Stat")
                        .HasForeignKey("Aros.Api.Data.Entities.TtsClipStat", "TtsClipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TtsClip");
                });

            modelBuilder.Entity("Aros.Api.Data.Entities.TtsClip", b =>
                {
                    b.Navigation("Stat");
                });
#pragma warning restore 612, 618
        }
    }
}
