// <auto-generated />
using System;
using Aros.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Aros.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260412210310_VocabTrainer")]
    partial class VocabTrainer
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Aros.Api.Data.Entities.TestAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Correct")
                        .HasColumnType("boolean");

                    b.Property<int>("TestSessionId")
                        .HasColumnType("integer");

                    b.Property<int>("TimeTakenMs")
                        .HasColumnType("integer");

                    b.Property<int>("VocabEntryId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TestSessionId");

                    b.HasIndex("VocabEntryId");

                    b.ToTable("TestAnswers");
                });

            modelBuilder.Entity("Aros.Api.Data.Entities.TestSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("TakenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("VocabListId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("VocabListId");

                    b.ToTable("TestSessions");
                });

            modelBuilder.Entity("Aros.Api.Data.Entities.VocabEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SourceWord")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TargetWord")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("VocabListId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("VocabListId");

                    b.ToTable("VocabEntries");
                });

            modelBuilder.Entity("Aros.Api.Data.Entities.VocabList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourceLanguage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TargetLanguage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("VocabLists");
                });

            modelBuilder.Entity("Aros.Api.Data.Entities.TestAnswer", b =>
                {
                    b.HasOne("Aros.Api.Data.Entities.TestSession", "TestSession")
                        .WithMany("Answers")
                        .HasForeignKey("TestSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Aros.Api.Data.Entities.VocabEntry", "VocabEntry")
                        .WithMany("TestAnswers")
                        .HasForeignKey("VocabEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TestSession");

                    b.Navigation("VocabEntry");
                });

            modelBuilder.Entity("Aros.Api.Data.Entities.TestSession", b =>
                {
                    b.HasOne("Aros.Api.Data.Entities.VocabList", "VocabList")
                        .WithMany("TestSessions")
                        .HasForeignKey("VocabListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VocabList");
                });

            modelBuilder.Entity("Aros.Api.Data.Entities.VocabEntry", b =>
                {
                    b.HasOne("Aros.Api.Data.Entities.VocabList", "VocabList")
                        .WithMany("Entries")
                        .HasForeignKey("VocabListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VocabList");
                });

            modelBuilder.Entity("Aros.Api.Data.Entities.TestSession", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("Aros.Api.Data.Entities.VocabEntry", b =>
                {
                    b.Navigation("TestAnswers");
                });

            modelBuilder.Entity("Aros.Api.Data.Entities.VocabList", b =>
                {
                    b.Navigation("Entries");

                    b.Navigation("TestSessions");
                });
#pragma warning restore 612, 618
        }
    }
}
